Repository gardener/etcd-wrapper, pull requests merged in 2024-01, with the labels that each got.

#21 [hotfix-v0.1] Set umask to 0077 for etcd process
  internal/app/app.go
Labels: area/security, kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, size/xs

#22 [hotfix-v0.1] Switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, merge/squash, needs/review, size/xs

#23 [hotfix-v0.1]Closing the ReadinessProbe discussion with GET call using --consistency=linearizable. (#13)
  docs/concepts/bootstrap.md
  internal/app/readycheck.go
Labels: reviewed/ok-to-test, needs/review, size/xs
